---
npmRegistries:
  //registry.npmjs.org/:
    npmAuthToken: "${NPM_PUBLISH_TOKEN:-invalid}"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

logFilters:
  - code: YN0060 # INCOMPATIBLE_PEER_DEPENDENCY
    level: error
  - code: YN0002 # MISSING_PEER_DEPENDENCY
    level: error
