name: Release

on:
  push:
    tags:
      - "v*"

env:
  CI: 1
  ARTIFACT_DIR: ./artifacts

jobs:
  release:
    name: Publish Yarn Plugin Licenses
    runs-on: ubuntu-20.04
    steps:
        - uses: actions/checkout@v4.0.0
        - uses: ./.github/actions/detect-env
        - name: Setup Node.js
          uses: actions/setup-node@v3.3.0
          with:
            node-version: ${{ env.NODE_VERSION }}
        - name: Create artifacts directory
          run: mkdir -p ${{ env.ARTIFACT_DIR }}
        - name: Restore yarn cache
          id: yarn-cache
          uses: actions/cache@v2
          with:
            path: |
              ./.yarn
              ./.pnp.*
            key: ${{ env.NODE_VERSION }}-${{ hashFiles('yarn.lock') }}
        - name: Install dependencies
          run: yarn install --immutable
        - name: Build Package
          run: yarn build
        - name: Publish Package
          run: echo "No publish capability at the moment."
        - name: Upload Artifacts
          if: ${{ always() }}
          uses: actions/upload-artifact@v3
          with:
            name: reports-and-build-artifacts
            path: |
                ${{ env.ARTIFACT_DIR }}
